### ISSUE TITLE
Incomplete countermeasures list

### ISSUE THREAD

**Issue by Polpetta** [Polpetta/CNSNotes#4]
**Description**
Missing the second bullet in the list of countermeasures on cache privacy on CCN.
File: section/22-Les06102016.tex
**Other issues**
None

**Comment by mdipirro** [comment]
I added the missing bullet and some other informations about countermeasures

**Comment by Polpetta** [comment]
Great, Thanks!

Il 11 ott 2016 12:38, "Matteo Di Pirro" notifications@github.com ha
scritto:
